# Generated by Django 2.0.8 on 2020-03-06 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Act',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('actorid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('photo', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Expect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('title', models.CharField(blank=True, default='', max_length=100)),
                ('genres', models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Animation', 'Animation'), ('Children', 'Children'), ('Comedy', 'Comedy'), ('Crime', 'Crime'), ('Documentary', 'Documentary'), ('Drama', 'Drama'), ('Fantasy', 'Fantasy'), ('Film-Noir', 'Film-Noir'), ('Horror', 'Horror'), ('Musical', 'Musical'), ('Mystery', 'Mystery'), ('Romance', 'Romance'), ('Sci-Fi', 'Sci-Fi'), ('Thriller', 'Thriller'), ('War', 'War'), ('Western', 'Western')], default='', max_length=100)),
                ('movieid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('year', models.CharField(max_length=4)),
                ('length', models.CharField(max_length=10)),
                ('rate', models.IntegerField(default=0)),
                ('poster', models.URLField(default='')),
                ('plot', models.CharField(max_length=500)),
                ('trailer', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Popularity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.IntegerField(default=0)),
                ('movieid', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='movie.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='Seen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('movieid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movie.Movie')),
            ],
        ),
        migrations.AddField(
            model_name='expect',
            name='movieid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movie.Movie'),
        ),
        migrations.AddField(
            model_name='act',
            name='actorid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movie.Actor'),
        ),
        migrations.AddField(
            model_name='act',
            name='movieid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movie.Movie'),
        ),
    ]
