# Generated by Django 2.0.8 on 2020-04-14 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20200306_0413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='act',
            name='actorid',
        ),
        migrations.RemoveField(
            model_name='act',
            name='movieid',
        ),
        migrations.RemoveField(
            model_name='expect',
            name='movieid',
        ),
        migrations.RemoveField(
            model_name='popularity',
            name='movieid',
        ),
        migrations.RemoveField(
            model_name='seen',
            name='movieid',
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Act',
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='Expect',
        ),
        migrations.DeleteModel(
            name='Popularity',
        ),
        migrations.DeleteModel(
            name='Seen',
        ),
    ]
