# Generated by Django 2.0.8 on 2020-03-03 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0002_auto_20200302_2242'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_parent', models.BooleanField(default=False)),
                ('is_teacher', models.BooleanField(default=False)),
                ('is_principal', models.BooleanField(default=False)),
                ('phone', models.CharField(default='', max_length=60)),
                ('description', models.TextField(default='')),
                ('full_name', models.CharField(default='', max_length=60)),
            ],
            options={
                'verbose_name': '帐户管理',
                'verbose_name_plural': '帐户管理',
            },
        ),
    ]
